Importing the important libraries required that is pandas and numpy for the **project**

In [3]:
import pandas as pd
import numpy as np

We are getting the dataset and loading it

In [4]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

We have the data in dataset in dictionaries format.now we are printing the keys of the irisdataset

In [5]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))


Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


Now we are printing the value in the key DESCR

In [6]:
print(iris_dataset['DESCR'][:193]+"\n....")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
....


Printing the target names that we have in our dataset that is the types of flowers we have.

In [7]:
print("Target names:{}".format(iris_dataset['target_names']))


Target names:['setosa' 'versicolor' 'virginica']


Printing the features of data points:

In [8]:
print("Features names:\n{}".format(iris_dataset['feature_names']))

Features names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Printing the type of data of our dataset:

In [9]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


Printing the shape of our dataset:

In [10]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


[Printing the first five columns of our dataset to have a glance look

In [11]:
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


printing the type of data of target in dataset:

In [12]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


printing the shape of data of target in our dataset

In [13]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


printing the target data values:

In [14]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


creating a model for our project using sklearn framework

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

printing the shapes of X_train and y_train and X_test and y_test

In [16]:
print("X_train shape:{}".format(X_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("y_test shape:{}".format(y_test.shape))

X_train shape:(112, 4)
y_train shape:(112,)
X_test shape:(38, 4)
y_test shape:(38,)


we are using kneighbors algorithm to classsify the know the  data entry point

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

We are training the our model using train dataset

In [18]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

creating a new data entry point of different features:

In [19]:
X_new = np.array([[5,2.9,1,0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


predicting the category of new data entry point:

In [20]:
prediction= knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name:{}".format(iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name:['setosa']


We are testing the all the test dataset  we have using our model

In [21]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


We are finding the accuracy of our model and printing the score

In [22]:
print("Test set score: {}".format(np.mean(y_pred==y_test)))

Test set score: 0.9736842105263158
